blank_issues_enabled: false
contact_links:
  - name: PureScript Discourse
    url: https://discourse.purescript.org/
    about: Ask and answer questions on the PureScript discussion forum.
  - name: PureScript Discord
    url: https://discord.com/invite/sMqwYUbvz6/
    about: Ask and answer questions on the PureScript chat.
